# Frontend/Dockerfile/ React
FROM node:18-alpine

# set work directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# copy all files
COPY . .

# Expose frontend port 

EXPOSE 3000

# Run app
CMD ["npm", "start"]

